run:
  timeout: 2m
  go: '1.19'

linters:
  disable:
    - wrapcheck
    - varnamelen
    - exhaustivestruct
    - exhaustruct
    - golint
    - wsl
    - funlen
    - paralleltest
    - forbidigo
    - cyclop
    - nosnakecase
    - scopelint

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused